services:
    db:
        container_name: postgres
        image: postgres
        environment:
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
            POSTGRES_DB: mydatabase
        ports:
            - 5432:5432
        healthcheck:
            test: ["CMD-SHELL","pg_isready -U myuser"]
            interval: 10s
            timeout: 5s
            retries: 3
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - mynetwork
    companies-app:
        container_name: companies-app
        build:
            context: ./xmCompanies
            dockerfile: Dockerfile
        environment:
            MY_HOST: postgres
        ports:
            - 8080:8080
        depends_on:
            db:
                condition: service_healthy
        networks:
            - mynetwork
networks:
    mynetwork:
        name: my-network